name: Spotify History Fetcher

on:
  schedule:
    - cron: "0 */4 * * *"   # Cada 4 horas
  workflow_dispatch:

jobs:
  fetch-history:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install spotipy pandas

      - name: Run script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
        run: |
          python spotify_script.py

      - name: Upload CSV Artifact
        uses: actions/upload-artifact@v3
        with:
          name: recent-tracks
          path: recent_tracks.csv
