name: Spotify History Fetcher

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  fetch-history:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repo (solo lectura es suficiente)
      - name: Check out repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: pip install spotipy pandas psycopg2-binary

      # --- Paso para probar conexión a la base de datos ---
      - name: Test PostgreSQL connection
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          PGPASSWORD=$DB_PASSWORD psql -4 -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "\conninfo"

      # 4️⃣ Ejecutar script de Spotify (con DB)
      - name: Run Spotify script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          SPOTIPY_CACHE: ${{ secrets.SPOTIPY_CACHE }}

          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -U $DB_USER -d $DB_NAME -p $DB_PORT -c "\conninfo"

