name: Run Spotify script

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  fetch-history:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repo (solo lectura es suficiente)
      - name: Check out repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: pip install spotipy pandas psycopg2-binary

      # 4️⃣ Ejecutar script de Spotify (con DB)
      - name: Run Spotify script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          SPOTIPY_CACHE: ${{ secrets.SPOTIPY_CACHE }}

          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: python ingestion/spotify_auto_history.py
